import { displayDate } from '../utils/dateUtils.js';

const MOOD_SYMBOLS = {
  Expanding: '▲', Tightening: '◆', Fragile: '⚠', Cooling: '▼',
  Stabilizing: '●', Volatile: '⚡', Overheated: '🔴', Constrained: '■', Optimistic: '★'
};

export function toMarkdown(report) {
  const lines = [];
  const dateStr = displayDate(report.report_date);

  lines.push(`# COMMODITY TRANSLATOR`);
  lines.push(`## Daily Signal Report — ${dateStr}`);
  lines.push('');
  lines.push('> *Signals from the physical economy before the headlines fully arrive.*');
  lines.push('');
  lines.push('---');
  lines.push('');

  if (report.top_3_signals?.length) {
    lines.push('## TOP 3 SIGNALS TO POST TODAY');
    lines.push('');
    for (const top of report.top_3_signals) {
      const sig = report.signals.find(s => s.id === top.signal_id);
      lines.push(`### ${top.rank}. ${sig?.title || top.signal_id}`);
      lines.push(`**Why it stands out:** ${top.why_it_stands_out}`);
      lines.push(`**Best visual direction:** ${top.best_visual_direction}`);
      lines.push(`**Best platform:** ${top.best_platform_fit}`);
      lines.push('');
    }
    lines.push('---');
    lines.push('');
  }

  lines.push(`## TODAY'S SIGNALS`);
  lines.push('');

  for (const [i, signal] of (report.signals || []).entries()) {
    const moodSymbol = MOOD_SYMBOLS[signal.industrial_mood] || '●';
    lines.push(`---`);
    lines.push('');
    lines.push(`### Signal ${i + 1} — ${signal.title}`);
    lines.push(`**Commodity:** ${signal.commodity} | **Mood:** ${moodSymbol} ${signal.industrial_mood} | **Story Score:** ${signal.storytelling_score}/10`);
    lines.push('');
    lines.push(`**What Happened**`);
    lines.push(signal.what_happened);
    lines.push('');
    lines.push(`**Why This Matters**`);
    lines.push(signal.why_this_matters);
    lines.push('');
    lines.push(`**Downstream Implications**`);
    lines.push(signal.downstream_implications);
    lines.push('');
    lines.push(`**Content Hooks**`);
    lines.push(`- 📣 **Short Hook:** ${signal.content_hooks?.short_social_hook || ''}`);
    lines.push(`- ⚠ **Factory Weather Alert:** ${signal.content_hooks?.factory_weather_alert || ''}`);
    lines.push(`- 👥 **Why Normal People Care:** ${signal.content_hooks?.why_normal_people_care || ''}`);
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(`*Generated by Commodity Translator on ${report.generated_at}*`);
  if (report.usage) {
    const cached = report.usage.cache_read_tokens ? ` | Cache: ${report.usage.cache_read_tokens} tokens` : '';
    lines.push(`*Tokens: ${report.usage.input_tokens} in / ${report.usage.output_tokens} out${cached}*`);
  }

  return lines.join('\n');
}

export function toSocialPackMarkdown(packData) {
  const lines = [];
  lines.push(`# COMMODITY TRANSLATOR — SOCIAL POST PACK`);
  lines.push(`## ${displayDate(packData.date)}`);
  lines.push('');
  lines.push('*Copy-paste ready. Top 3 signals only.*');
  lines.push('');

  for (const post of packData.posts) {
    const { signal, rank } = post;
    lines.push('---');
    lines.push('');
    lines.push(`# ${rank}. ${signal.title}`);
    lines.push(`*${signal.commodity} · ${signal.industrial_mood} · Score: ${signal.storytelling_score}/10*`);
    lines.push('');

    lines.push(`## LinkedIn`);
    lines.push(`> **${post.linkedin.length} words approx**`);
    lines.push('');
    lines.push(post.linkedin);
    lines.push('');

    lines.push(`## X / Twitter`);
    lines.push(`> **${post.x_post.length} characters**`);
    lines.push('');
    lines.push(post.x_post);
    lines.push('');

    if (post.tiktok?.hook) {
      lines.push(`## TikTok / Reels Concept`);
      lines.push(`**Hook:** ${post.tiktok.hook}`);
      lines.push(`**Intro (5-7s):** ${post.tiktok.intro_5_7_seconds}`);
      lines.push(`**Visual idea:** ${post.tiktok.visual_idea}`);
      if (post.tiktok.scene_beats?.length) {
        lines.push(`**Scene beats:**`);
        post.tiktok.scene_beats.forEach(b => lines.push(`- ${b}`));
      }
      lines.push(`**On-screen text:** ${post.tiktok.on_screen_text}`);
      lines.push(`**Voiceover:** ${post.tiktok.voiceover}`);
      lines.push(`**CTA:** ${post.tiktok.cta}`);
      lines.push('');
    }

    lines.push(`## Newsletter Blurb`);
    lines.push(post.newsletter);
    lines.push('');

    lines.push(`## Visual Prompt (AI Image/Video)`);
    lines.push(`\`\`\``);
    lines.push(post.visual_prompt);
    lines.push(`\`\`\``);
    lines.push('');
  }

  return lines.join('\n');
}
